name = "rottentheme"
license = "AGPL-3.0"
licenselink = "https://github.com/rottenwheel/rottentheme/raw/master/COPYING"
description = "Hugo theme for Rottenwheel"
homepage = "https://github.com/rottenwheel/rottentheme"
tags = ["minimal", "dark", "blog"]
features = []
min_version = "0.41"

authors = [
    {name = "Siren", homepage = "digilol.net"},
]

[original]
    author = "Stnby"
    homepage = "digilol.net"
    repo = "https://gitlab.com/kernal/hugo-kernal"
